### DISCUSSION TITLE
Reference generated classnames

### DISCUSSION THREAD

**Discussion by maxburs** [microsoft/griffel#257] [Q&A] [answered]
Is there any way to reference a generated class name in a different `makeStyles` call or the same one?

For example, if I was to try and convert a css module file that looks like this, how would I do it?

```css
/* Same file class references. I'd expect this to generate 3 unique classes. */
.element1 { }
.element2 { }

.open.element1 { }
.open.element2 { }
```

```css
/* Different file class references (https://github.com/css-modules/css-modules#composing-from-other-files) */
.button {
  color: white;
}

.button {
  composes darkMode from '../pageStyles.css';
  color: black;
}
```

I found this reference to "nested selectors" in the docs, but it uses global names for the child selectors.
```ts
import { makeStyles } from '@griffel/react';

const useClasses = makeStyles({
  root: {
    '& .foo': { color: 'green' },
    '&.bar': { color: 'red' },
  },
});
```
