### DISCUSSION TITLE
Descendant combinator in griffel styles

### DISCUSSION THREAD

**Discussion by Cam-Bloom** [microsoft/griffel#524] [Q&A] [answered]
I am currently working on a project which uses fluent ui and griffel, I have some css code that i would like to replicate in griffel but unsure how to do so.

I my situation is using the accordian from fluent, but we have the situation where we have nested accordians which are autogenerated, I need to be able apply the style to the child accordian in the following way, using background colour red as an example

``` css
.fui-AccordionItem .fui-AccordionItem {
    background-color: red;
}
```

Is there a way to achieve the same in griffel?

**Comment by layershifter** [comment, marked as answer]
@Cam-Bloom you can do following ⬇️ 

### global

```tsx
makeStyles({
  global: {
    ':global(.item)': {
      color: 'red',
    },
  },
});
```

```css
.item .fauc13k {
  color: red;
}
```

### nested

```ts
makeStyles({
  global: {
    '& .item': {
      color: 'red',
    },
  },
});
```

```css
.fn4exxb .item {
  color: red;
}
```

**Comment by Cam-Bloom** [comment]
@layershifter Sorry if I am missing something, but have made reproductions of my examples, would you be able to point out where im going wrong, thanks in advance

With CSS, what im trying to achieve
https://stackblitz.com/edit/vitejs-vite-nxazex?file=src%2FApp.tsx,src%2FCssAccordian.tsx,src%2Faccordian.css&terminal=dev

With Griffel 
https://stackblitz.com/edit/vitejs-vite-cmuaxv?file=src%2FApp.tsx,src%2FGriffelAccordian.tsx&terminal=dev

**Reply by layershifter** [reply]
```css
.fui-AccordionItem .fui-AccordionItem {
/*   ^ host             ^ selector */
  background-color: red;
}
```

```ts
const useStyles = makeStyles({
  global: {
    '& .fui-AccordionItem': {
      backgroundColor: 'red',
    },
  },
});
```

```tsx
<AccordionItem className={styles.global}> /* host */
  <AccordionItem value="1-1">
```

https://stackblitz.com/edit/vitejs-vite-vulhgc?file=src%2FApp.tsx,src%2FGriffelAccordian.tsx&terminal=dev
