### ISSUE TITLE
Inconsistent output of `r` if no units are specified

### ISSUE THREAD

**Issue by smhigley** [microsoft/griffel#119]
If the `r` SVG CSS prop is specified with no units, griffel will generate a className + style for Chromium browsers, but will create a className with no style for Firefox. You can see the difference in this codesandbox on each browser:
https://codesandbox.io/s/musing-roentgen-r9i7g5?file=/src/App.js

Firefox has these classNames/styles:
```css
.f1uzb8hk { width: 45px; }
.fvfw249 { height: 45px; }
.f4a1i41 { cx: 50%; }
.f15az5lx { cy: 50%; }
.f10o6nd5 { }
```

Chromium has these:
```css
.f1uzb8hk { width: 45px; }
.fvfw249 { height: 45px; }
.f4a1i41 { cx: 50%; }
.f15az5lx { cy: 50%; }
.f10o6nd5 { r: 10; }
```

It seems like it would be more predictable and much easier to debug if griffel were to output the `r` style regardless of browser support for units/unitless values.
