### ISSUE TITLE
core: create a chained selector with :global

### ISSUE THREAD

**Issue by ling1726** [microsoft/griffel#178]
The current global selector creates a style that is a parent selector

```js
':global(.parent)': {
  color: 'red',
},
```

```css
.parent .fztiaq5 {
  color: red;
}
```

The above will work with
```html
<div class="parent">
  <div class=" .fztiaq5" />
</div>
``` 

How can one created a chained class selector with Griffel ?

```css
.same-element.fztiaq5 {
  color: red;
}
```

```html
<div class=".same-element .fztiaq5" />
```

**Comment by layershifter** [comment]
## References

- https://cssinjs.org/jss-plugin-global/?v=v10.9.2
   Does not match this case as there is no such API, https://codesandbox.io/s/zealous-sea-t5i98h?file=/src/index.js:234-286
- https://github.com/vercel/styled-jsx#one-off-global-selectors
  _It was close..._ https://codesandbox.io/s/solitary-bush-r38jx7?file=/pages/index.js:218-369

  ```jsx
    <style jsx>{`
      :global(body) .small {
        color: orange;
      }
      :global(body).large {
        color: orange;
      }
    `}</style>
  ```
  ⬇️⬇️⬇️
  ```css
   body .small.jsx-2179285284{color:orange;}
   body .large.jsx-2179285284{color:orange;}
   ```
- CSS modules does exactly what is expected
  https://codesandbox.io/s/jovial-carson-ht6k0y?file=/src/styles.module.css
  ```css
  :global(body) .App {
    color: blue;
  }

  :global(body).App {
    color: pink;
  }
  ```
  ⬇️⬇️⬇️
  ```css
  body ._src_styles_module__App {
    color: blue;
  }

  body._src_styles_module__App {
    color: pink;
  }
  ```

**Comment by layershifter** [comment]
There are two problems:
- We can't change current API to avoid breaking changes
- We will need something simple and straightforward

From straightforward perspective the pair of `':global(body )'` & `':global(body)'` looks simple and works as CSS modules, but will be a breaking change 🙃

I am leaning towards:
- `':global(body)'` (keeps existing) & `':global(body&)'` (removes the space)
- `':global(body)'` (keeps existing) & ``':prefix(body)'` (removes the space)

Both look ugly TBH 🥹 Opinions?

**Comment by ling1726** [comment]
we could use `':global(body&)'` and  `':global(body &)'` and then simply advertise them 2 in all public docs. We could then add deprecation warnings for `':global(body)'` both at runtime and build time.

forcing users to use the ampersand seems better as it's more explicit, and it's something that really does make a difference in CSS.

**Comment by miroslavstastny** [comment]
> maybe not even deprecate we could just assume that he result will be ':global(body&)' if no ampersand is applied

But the current behavior is `:global(body &)`, right? So what you are proposing would be a breaking change.

**Comment by ling1726** [comment]
> But the current behavior is `':global(body &)'`, right? So what you are proposing would be a breaking change.

Sorry I meant `':global(body &)'` I've edited the original commet

**Comment by layershifter** [comment]
I think that we can go with `:global(body &)` and additionally handle `:global(body&)` in the same way as `:global(body)`.

**Comment by ling1726** [comment]
> I think that we can go with `:global(body &)` and additionally handle `:global(body&)` in the same way as `:global(body)`.

But isn't that the breaking change ?

**Comment by layershifter** [comment]
> But isn't that the breaking change ?

Why? We will keep `:global(body)` as it is.

**Comment by ling1726** [comment]
> > But isn't that the breaking change ?
> 
> Why? We will keep `:global(body)` as it is.

OK this is funny, just to be clear is this what we are talking about ?

* `:global(body)` -> `:global(body &)`
* `:global(body &)` -> `body .fd144d`
* `:global(body&)` -> `body.fd144d`

**Comment by layershifter** [comment]
- `:global(body)` -> `body.fd144d`
- `:global(body&)` -> `body.fd144d`
- `:global(body &)` -> `body .fd144d`

Makes sense?

**Comment by ling1726** [comment]
👀

![image](https://user-images.githubusercontent.com/20744592/183097105-4f77952b-4859-440d-bfd7-6a10ca90d632.png)

**Comment by layershifter** [comment]
After spending some time and thinking about I came to following conclusion: there is no need in this feature as it's already there.

For example, you can't create `.foo.f1lw17ff`, but you can `.f1lw17ff.foo`:

```ts
 makeStyles({
  root: {
    '&.foo': { color: 'red' }
  },
});
```

There is a problem with elements as we produce an invalid selector:

```ts
makeStyles({
  root: {
    '&body': { color: 'red' }
  },
})
```

```css
.f115m9dlbody { /* 🤯 */
  color: red;
}
```

I created a separate issue for it
