### ISSUE TITLE
core: comma-separated nested selectors are not handled properly

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#204]
Version: `@griffel/core@1.6.0`.
Repro: https://stackblitz.com/edit/node-sovmxb?file=index.test.js

---

```js
makeStyles({
  ":hover,:focus-within": {
    "::before": {
      color: "orange"
    }
  }
});
```

It's expected that following code will generate this rule:

```css
.fij4gri:hover::before,
.fij4gri:focus-within::before {
  color: orange;
}
```

But it generates:

```css
.fij4gri:hover,
/*           👆 "::before" is lost */
.fij4gri:focus-within::before {
  color: orange;
}
```

It's a real usage in Fluent UI: https://github.com/microsoft/fluentui/blob/94ab82dd00db0bf177908e7ccc60125efaa4e22d/packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts#L113-L121
