### ISSUE TITLE
core: :global() selector does not handle spaces

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#206]
**Version**: `@griffel/core@1.6.0`.
**Repro**: https://stackblitz.com/edit/node-ab1ctm?file=index.test.js

---

```js
makeStyles({
  ":global(body) :focus": { color: "green" }
});
```

It's expected that following code will generate this rule:

```css
body .frou13r :focus {
  color: green;
}
```

But it generates:

```css
body .frou13r:focus {
/*           👆 " " is lost */
  color: green;
}
```
