### ISSUE TITLE
core: & with some selectors produces an invalid result

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#222]
Comes from #178.

```ts
 makeStyles({
  root: {
    '&.foo': { color: 'red' }
  },
});
```

Produces correct result ✅

```css
.f1lw17ff.foo {
  color: red;
}
```

---

While `&body`:

```ts
makeStyles({
  root: {
    '&body': { color: 'red' }
  },
})
```

Produces a wrong result 🚨

```css
.f115m9dlbody { /* 🤯 oops */
  color: red;
}
```

- [ ] check also `[data]` selectors
