### ISSUE TITLE
Merge like media queries in extracted CSS

### ISSUE THREAD

**Issue by NotWoods** [microsoft/griffel#311]
With the webpack extraction plugin, we can end up with many similar CSS media queries immediately after each other. These should be collapsed to save some bytes from the output CSS file.

# Example
## Currently generated CSS
```css
@media screen and (min-width: 700px) {
  .f15y6sl0 {
    margin-bottom: auto;
  }
}
@media screen and (min-width: 700px) {
  .f1mmeaxr {
    margin-left: auto;
  }
  .f13yy761 {
    margin-right: auto;
  }
}
@media screen and (min-width: 700px) {
  .fo29on3 {
    width: 369px;
  }
}
@media screen and (prefers-reduced-motion: reduce) {
  .folzdkc > svg > circle.fui-Spinner__Tail {
    -webkit-animation-duration: 0.01ms;
    animation-duration: 0.01ms;
  }
}
@media screen and (prefers-reduced-motion: reduce) {
  .fhlfkde > svg > circle.fui-Spinner__Tail {
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
  }
}
```
## Collapsed media queries

```css
@media screen and (min-width: 700px) {
  .f15y6sl0 {
    margin-bottom: auto;
  }
  .f1mmeaxr {
    margin-left: auto;
  }
  .f13yy761 {
    margin-right: auto;
  }
  .fo29on3 {
    width: 369px;
  }
}
@media screen and (prefers-reduced-motion: reduce) {
  .folzdkc > svg > circle.fui-Spinner__Tail {
    -webkit-animation-duration: 0.01ms;
    animation-duration: 0.01ms;
  }
  .fhlfkde > svg > circle.fui-Spinner__Tail {
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
  }
}
```
