### ISSUE TITLE
webpack-extraction-plugin: @media in __resetStyles() creates broken CSS

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#321]
`@griffel/webpack-extraction-plugin` produces invalid CSS when `__resetStyles()` contains a `@media` rule.

### Input

```ts
import { __resetStyles } from "@griffel/react";
export const useClassName = /*#__PURE__*/ __resetStyles("r13wlxb8", null, [
  ".r13wlxb8{line-height:0;}",
  "@media screen and (prefers-reduced-motion: reduce){.r13wlxb8{transition-duration:0.01ms;}}"
]);
```

### Expected output

```css
.r13wlxb8 {
  line-height: 0;
}
@media screen and (prefers-reduced-motion: reduce) {
  .r13wlxb8 {
    transition-duration: 0.01ms;
  }
}, /* 👈 "," at end */
```

```
    SyntaxError: CssSyntaxError: Unknown word (3:116)
      1 |
      2 | /** griffel.css **/
    > 3 | .r13wlxb8{line-height:0;}@media screen and (prefers-reduced-motion: reduce){.r13wlxb8{transition-duration:0.01ms;}},
        |                                                                                                                    ^

      179 |
      180 |       resultCSS = fixLineEndings(
    > 181 |         prettier.format(result.cssOutput, {
          |                  ^
      182 |           ...prettierConfig,
      183 |           parser: 'css',
      184 |         }),
```

### Expected output

```css
.r13wlxb8 {
  line-height: 0;
}
@media screen and (prefers-reduced-motion: reduce) {
  .r13wlxb8 {
    transition-duration: 0.01ms;
  }
}
```
