### ISSUE TITLE
core/babel-preset: duplicated rules with at-rules

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#372]
The following snippet with flipping properties in RTL causes CSS rule duplication:

```ts
import { makeStyles, shorthands } from "@griffel/core";

export default makeStyles({
  root: {
    "@media(forced-colors: active)": {
      paddingLeft: "8px",
      paddingRight: "8px"
    },
    "@supports (display: flex)": {
      paddingLeft: "4px",
      paddingRight: "4px"
    }
  }
});
```

This affects both CSS extraction and transformed code:

```js
// Transformed code
export const useStyles = __styles(
  {
    root: {
      cvzfql: ["f13wceqr", "fmtq1hn"],
      g42fl4: ["fmtq1hn", "f13wceqr"],
      B6rh290: ["f16pi78z", "fem5dos"],
      rth2jb: ["fem5dos", "f16pi78z"]
    }
  },
  {
    m: [
      [
        "@media (min-width: 600px){.f13wceqr{padding-left:4px;}.fmtq1hn{padding-right:4px;}}",
        {
          m: "(min-width: 600px)"
        }
      ],
      [
        "@media (min-width: 600px){.fmtq1hn{padding-right:4px;}.f13wceqr{padding-left:4px;}}",
        {
          m: "(min-width: 600px)"
        }
      ]
    ],
    t: [
      "@supports (display: flex){.f16pi78z{padding-left:4px;}.fem5dos{padding-right:4px;}}",
      "@supports (display: flex){.fem5dos{padding-right:4px;}.f16pi78z{padding-left:4px;}}"
    ]
  }
);
```

```css
// Extracted CSS
@media (forced-colors: active) {
  .f1xnl3gg {
    padding-left: 8px;
  }

  .fyzjxl6 {
    padding-right: 8px;
  }
}

@media (forced-colors: active) {
  .fyzjxl6 {
    padding-right: 8px;
  }

  .f1xnl3gg {
    padding-left: 8px;
  }
}
```

[Playground](https://griffel.js.org/try-it-out/?code=JYWwDg9gTgLgBAbziAhgawKYGUYE8A2GAzgDRxEAW0MFKAdgCZFwC%2BcAZlBCHAOQACAcyjB27DPgD0AY2gZeAbgBQSjAA9IsOAwzsUAV3zxUmHAWIAKBErhwuEGAC5EN2334gMDYCgvto0l4AtLL40ETOKNIwwABuGACUvM7Wbm5gKAzedIIAMrpOfAAcYGq8JK5pGVnAOQBKwIIUhbwlZRVpLB2sFSwJykA)
