### ISSUE TITLE
core: @layer does not work properly with makeResetStyles

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#373]
```ts
import { makeStyles, shorthands } from "@griffel/react";

const useClasses = makeResetStyles({
  "@layer utilities": {
    color: "pink"
  }
});
```

### Expected result

```css
@layer utilities {
  .r1vddiyf {
    color: pink;
  }
}
```

### Actual result

```css
@layer utilities {
  color: pink;
}
```
