### ISSUE TITLE
@containe at rule used in makeStyles  "yanks" out the shared attribute

### ISSUE THREAD

**Issue by jvince** [microsoft/griffel#399]
For a given style:

```
const useAppStyles = makeStyles({
  ....otherStyles,
  header: {
    backgroundColor: "pink",
    "@container bar (width > 400px)": {
      backgroundColor: "magenta",
      color: "orange"
    },
    "@media (min-width: 600px)": {
      backgroundColor: "green"
    }
  }
});}
```

The `backgroundColor` attribute is removed from the base style and the `@media` block when defined in the `@container` block.
Is this the expected behavior, or the `backgroundColor` should not be touched outside of the `@container` block?
If `backgroundColor` is removed from the `@container` block everything is working as expected.

Test project: https://codesandbox.io/s/griffel-container-forked-h7v2qw?file=/src/App.js

**Comment by layershifter** [comment]
@jvince not sure that I understand what do you mean.

```ts
makeStyles({
  root: {
    backgroundColor: "pink",
    "@container bar (width > 400px)": {
      backgroundColor: "magenta", // Comment out to get the backgroundColor working
      color: "orange"
    },
    "@media (min-width: 600px)": {
      backgroundColor: "green"
    }
  }
});
```

⬇️⬇️⬇️

```css
.fnf68zh {
  background-color: pink;
}

@container bar (width > 400px) {
  .f141m0x3 {
    background-color: magenta;
  }
}

@container bar (width > 400px) {
  .f14w8xz5 {
    color: orange;
  }
}

@media (min-width: 600px) {
  .ft14zye {
    background-color: green;
  }
}
```

https://griffel.js.org/try-it-out/?code=JYWwDg9gTgLgBAbziAhgawKYGUYE8A2GAzgDRxEAW0MFKAdgCZFwC%2BcAZlBCHAOQACAcyjB27DPgD0AY2gZeAbgBQSjAA9IsOAwzsUAV3zxUmHAWIAKBErhwuEGAC5EN23ABGKaWmER9jAGEIfGhnACIwYDo0MJJXWzD%2BWToYFCiMKA8UTIsAd2AGGjgAPjgAFgAGCrA1AEow52s3N09vX38GIJCocNRBDBSUWLhJSTggkBAB%2BD94GAg4frmKDCy2rg6u6Dhc6DQowXi3WW7w6Hp%2BsKOWOObEqYZgFDgLECiAWnzCimcANiqavVGkdbK0fBtAsFQnAwsIMAMrs0WK5kSxasogA

---

As I see all CSS rules are generated. Do I miss anything?
