### ISSUE TITLE
multiple @container rules ignored (only last rule is applied)

### ISSUE THREAD

**Issue by rgylesbedford** [microsoft/griffel#438]
When I use the following `makeStyles()` code, the last `@container` rule is included by Griffel and all others are ignored. Griffel is also ignoring the `backgroundColor: "red"` style.

```ts
const useAppStyles = makeStyles({
  root: {
    backgroundColor: "black",
    color: "white",
    ...shorthands.padding("15px", "15px", "15px", "15px")
  },
  container: {
    containerType: "inline-size"
  },
  header: {
    backgroundColor: "red",
    color: "black",
    "@container (min-width: 400px)": {
      "&" : {
        backgroundColor: "orange"
      },
    },
    "@container (min-width: 500px)": {
      "&" : {
        backgroundColor: "yellow"
      }
    },
    "@container (min-width: 600px)": {
      "&" : {
        backgroundColor: "green"
      }
    },
    "@container (min-width: 700px)": {
      "&" : {
        backgroundColor: "blue"
      }
    },
  }
});
```
For reference, I'm trying to translate the following CSS:

```css
.root {
  background-color: black;
  color: white;
  padding: 15px;
}
.container {
  container-type: inline-size;
}
.header {
  background-color: red;
  color: black;
}
@container (min-width: 400px) {
  .header {
    background-color: orange;
  }
}
@container (min-width: 500px) {
  .header {
    background-color: yellow;
  }
}
@container (min-width: 600px) {
  .header {
    background-color: green;
  }
}
@container (min-width: 700px) {
  .header {
    background-color: blue;
  }
}
```

Example sandbox with both versions:
https://codesandbox.io/s/griffel-container-forked-ljc8dn
