### ISSUE TITLE
Why do class definitions get broken up into single-rule classes?

### ISSUE THREAD

**Issue by SivanMehta** [microsoft/griffel#455]
In the [playground](https://griffel.js.org/try-it-out/?code=JYWwDg9gTgLgBAbziAhgawKYGUYE8A2GAzgDRxEAW0MFKAdgCZFwC%2BcAZlBCHAOQACAcyjB27DPgD0AY2gZeAbgBQSjAA9IsOAwzsUAV3zxUmHAWIAKBErhwuEGAC5EN23ABGKaWmER9jAGEIfGhnXigMBl4SV1swFAYGYDpBABldJz4ARgAGMDVeVxYYlgBKZSA), I created this class:

```js
import { makeStyles, shorthands } from '@griffel/core';

export default makeStyles({
  root: {
    backgroundColor: 'red',
    paddingLeft: '10px'
  },
});

```

which was resolved into the following css:

```css
.f3xbvq9 {
  background-color: red;
}

.frdkuqy {
  padding-left: 10px;
}

.f81rol6 {
  padding-right: 10px;
}
```

Why is this broken up into singleton rules in 3 classes, rather than a single class? I was expecting something similar to this:

```css
.f3xbvq9 {
  background-color: red;
  padding-left: 10px;
  padding-right: 10px;
}
```

Creating extra classes needlessly inflates the size of stylesheets, so why is this behavior default? Is there a way to create single class instead?
