### ISSUE TITLE
Next-sibling combinator (+) has unexpected behavior

### ISSUE THREAD

**Issue by AkimaLunar** [microsoft/griffel#613]
I have noticed that next-sibling combinator only works where the root class comes first. Is it an expected behavior or a bug?

✅ Works

```ts
export const useMyStyles= makeStyles({
  example: {
    color: 'red',
    '& + .some-class' : {
      color: 'blue',
    }
  }
})
```

❌ Doesn’t work

```ts
export const useMyStyles= makeStyles({
  example: {
    color: 'red',
    '.some-class + &' : {
      color: 'blue',
    }
  }
})
```

**Comment by layershifter** [comment]
@AkimaLunar what CSS output do you expect in both cases?

**Comment by AkimaLunar** [comment]
Hey, @layershifter! Is it an atomic CSS limitation that I am not seeing?

```css
.f15f830o + .some-class {
  color: blue;
}
```

vs

```css
.some-class + .f15f830o  {
  color: blue;
}
```

Is it a scenario where you need to use `makeResetStyles`, so you don't end up with something strange like:

```css
.some-class + .f15f830o  {
  color: blue;
}

.some-class + .fqsesyh {
  line-height: 1rem;
}

.some-class + .fns74iw  {
  font-weight: 800;
}
```
